pipeline:
  name: DevSecOps
  identifier: DevSecOps
  projectIdentifier: JoTestApp
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: CI
        identifier: Run_tests
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Python_tests
                  identifier: Run
                  spec:
                    connectorRef: account.harnessImage
                    image: python
                    shell: Bash
                    command: |-
                      pip install -r requirements/requirements.txt
                      pytest
                    imagePullPolicy: IfNotPresent
                  description: RUn python tests
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Docker
                  identifier: Docker
                  spec:
                    connectorRef: DockerhubJo
                    repo: jonathanbellemare1/devsecops
                    tags:
                      - <+pipeline.sequenceId>
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: JoGithubAccount
        repoName: API-FUN
        build: <+input>
